artist_tracks = {
    "Mainstreet": ["https://open.spotify.com/intl-pt/track/5t2RXNtjGIzKPGiNYSU6FG",
                   "https://open.spotify.com/intl-pt/track/7MybxBlifyFeyfds4x4g5p",
                   "https://open.spotify.com/intl-pt/track/1DFl6V6pItoSRoCDR6zzAy",
                   "https://open.spotify.com/intl-pt/track/315JaAW5Ed3C7rnKOGMg6e",
                   "https://open.spotify.com/intl-pt/track/5V3CmFA57izQ3cwZFEpmle",
                   "https://open.spotify.com/intl-pt/track/6Kow39MGiBWCypfj14oZ6A",
                   "https://open.spotify.com/intl-pt/track/6LKdX3mQwwOblLhBCfmGlU",
                   "https://open.spotify.com/intl-pt/track/0MW2WCZsE8BALPlGM9oVyd",
                   "https://open.spotify.com/intl-pt/track/49NyXYwAtRZcjTojDdffrz",
                   "https://open.spotify.com/intl-pt/track/1o3YckJFGqTcs4oHsTp6I8",
                   "https://open.spotify.com/intl-pt/track/095tiFEdBunjDaXo428cDj",
                   "https://open.spotify.com/intl-pt/track/15I6cAW7N022uQ51FJmRPB",
                   "https://open.spotify.com/intl-pt/track/2twZl1jsRbJRTNCE6VB6eW",
                   "https://open.spotify.com/intl-pt/track/6rCAD1L3H87qRNGGVli37l",
                   "https://open.spotify.com/intl-pt/track/6S00iFG7VSum4SgXoNXha8",
                   "https://open.spotify.com/intl-pt/track/3by89k8zGClgmQgz9SbtKp",
                   "https://open.spotify.com/intl-pt/track/5zHgKTl9uTZqUfdbszAU3W",
                   "https://open.spotify.com/intl-pt/track/79SdFOAZlkc2xrlNJPRrn6",
                   "https://open.spotify.com/intl-pt/track/44v9eNGRuwFDXzPWu2GkHP",
                   "https://open.spotify.com/intl-pt/track/63HYpMDcQo0Fryhmje08Bl",
                   "https://open.spotify.com/intl-pt/track/37LWZe5mdHIKuXBh8GuwlH",
                   "https://open.spotify.com/intl-pt/track/24Qz27YhZ8eVnJl6sD6hyd",
                   "https://open.spotify.com/intl-pt/track/6yadp6uXJpV1ZvKcu73Ji0",
                   "https://open.spotify.com/intl-pt/track/3n7ASTQanOp5milmESBqlt",
                   "https://open.spotify.com/intl-pt/track/1QjmBR1bqmh0fYrVnD9iU8",
                   "https://open.spotify.com/intl-pt/track/1BoMpKPeITtg3HN9Ursz5T",
                   "https://open.spotify.com/intl-pt/track/5cCwZJUf8QiCQGnyakhpmF",
                   "https://open.spotify.com/intl-pt/track/545IGh8s0x4tniaiBLHL6t",
                   "https://open.spotify.com/intl-pt/track/1EsgC6YzdQkKmPKB1QyEiE",
                   "https://open.spotify.com/intl-pt/track/76klxh7fnauuROKC2kDuHG",
                   "https://open.spotify.com/intl-pt/track/0cP0H3mezxubJHdDCUEMX4",
                   "https://open.spotify.com/intl-pt/track/5SO4R7IpqIBcm6LjUvKmlj",
                   "https://open.spotify.com/intl-pt/track/1KKnzHMySnYqkjwSHqgVVI",
                   "https://open.spotify.com/intl-pt/track/6iO7nBM2StwcPvuyblR0P4",
                   "https://open.spotify.com/intl-pt/track/152JuulFiSlmLQU1p3oM4b",
                   "https://open.spotify.com/intl-pt/track/1bQgCqHYpDvTs5QwEQX937",
                   "https://open.spotify.com/intl-pt/track/4Exjs0i5CFfKpIegAqcYOg",
                   "https://open.spotify.com/intl-pt/track/0J8LV0mKp1a2mBeiJTv1xZ",
                   "https://open.spotify.com/intl-pt/track/7DqtyR5w0QXD6BKnyawIm6",
                   "https://open.spotify.com/intl-pt/track/40JTPDvqaCP3hAKwczbshP",
                   "https://open.spotify.com/intl-pt/track/490GbBa2Apa3vNHcPkyJWO",
                   "https://open.spotify.com/intl-pt/track/1ltaaZhoXHHLQFYzyKSIGp",
                   "https://open.spotify.com/intl-pt/track/2oLCJDxRZYoEiLuSwanbjG",
                   "https://open.spotify.com/intl-pt/track/56xYjxmkJxnpBVQi6pLSiL",
                   "https://open.spotify.com/intl-pt/track/6rGOddAeZDBywYmeDYhJrQ",
                   "https://open.spotify.com/intl-pt/track/7eZCP5YHeqVsIGaPp8y9ac",
                   "https://open.spotify.com/intl-pt/track/7byTUdupcQ5dSRd3D9jAQo",
                   "https://open.spotify.com/intl-pt/track/0WYtu0wyQrJGlW1O8IYH1q",
                   "https://open.spotify.com/intl-pt/track/2HrjORyFBF3IFnXOAC3Rox",
                   "https://open.spotify.com/intl-pt/track/27iAEVwv6aMaICmXPkk50m",
                   "https://open.spotify.com/intl-pt/track/4BfppnNi6ZQTI8Ezo97zX6",
                   "https://open.spotify.com/intl-pt/track/0qzdA4ZdKqoTP4BEVpJdRu",
                   "https://open.spotify.com/intl-pt/track/5adH787aC7muiWC60s8Yvt",
                   "https://open.spotify.com/intl-pt/track/6jxE4XjFVSKF18kfo7FCl9",
                   "https://open.spotify.com/intl-pt/track/3QGxgNaqaFSpORp2OVLXHR",
                   "https://open.spotify.com/intl-pt/track/6CBdQXFI9nPUTVf51cWWxO",
                   "https://open.spotify.com/intl-pt/track/6jJiQk7l8SGVW2dfuG0IH2",
                   "https://open.spotify.com/intl-pt/track/2EQe3IsJqNfS8WACLeZnaY",
                   "https://open.spotify.com/intl-pt/track/6aqEqwMX0bnXO4pgEfXcPi",
                   "https://open.spotify.com/intl-pt/track/7xY5NUCid0WymfaXBZGhpW",
                   "https://open.spotify.com/intl-pt/track/0m5U5BkdjyDs0Fppkxvt2U",
                   "https://open.spotify.com/intl-pt/track/2VgNXyQcrsSyQdT4YyuFCu",
                   "https://open.spotify.com/intl-pt/track/7kOxU71fB54lrzu2GaZiNr",
                   "https://open.spotify.com/intl-pt/track/4sD1WFRLLoNMxgDHaTkF0I",
                   "https://open.spotify.com/intl-pt/track/5WSELUpi4GjDx3nRolKvSy",
                   "https://open.spotify.com/intl-pt/track/1IgyrKsjlZFo4EsQJtIbsa",
                   "https://open.spotify.com/intl-pt/track/06XgmjLenw60Y0VkCoxu8O",
                   "https://open.spotify.com/intl-pt/track/6EPTq7EQn8jrUPo3UoS61C",
                   "https://open.spotify.com/intl-pt/track/7IG7laqVpcvIIULrwWP5SA",
                   "https://open.spotify.com/intl-pt/track/3RuaQEnUtAYSblbk9K16u8",
                   "https://open.spotify.com/intl-pt/track/5Rm5tzLlpbBpUorSDETbjg",
                   "https://open.spotify.com/intl-pt/track/4VAo4FcgD6v9Ha9sRTn1Iv",
                   "https://open.spotify.com/intl-pt/track/3ZBRYFOmXvO0nQWbKWgIn3",
                   "https://open.spotify.com/intl-pt/track/68cPbG7hJnwDW9nPX1uQcX",
                   "https://open.spotify.com/intl-pt/track/2YHdQVG5x6XI8HmdcqGJnn",
                   "https://open.spotify.com/intl-pt/track/4U8MZkasPn6VfwlwG3egGt",
                   "https://open.spotify.com/intl-pt/track/3suLdq5ZeXRrhpsYIMWrAQ",
                   "https://open.spotify.com/intl-pt/track/0rRuJdTpQFw5O5pcVytvwm",
                   "https://open.spotify.com/intl-pt/track/7p7ucw8UgzpwYnCfEhCxxn",
                   "https://open.spotify.com/intl-pt/track/5nIGVYXsdnS86hhbhIty2B",
                   "https://open.spotify.com/intl-pt/track/2I26XWAyR6vffAzwhAxdqO",
                   "https://open.spotify.com/intl-pt/track/32IGREEfY97uQ19npMKIlO",
                   "https://open.spotify.com/intl-pt/track/1BGHVKmt3Z2FArfkAvujcI",
                   "https://open.spotify.com/intl-pt/track/3PEecVkDpSSxey4mVssneS",
                   "https://open.spotify.com/intl-pt/track/7b8kjWj4TKWmWo2LX9Lkiz",
                   "https://open.spotify.com/intl-pt/track/1CBjYXLotHrkiykMbI7EaU",
                   "https://open.spotify.com/intl-pt/track/4s2yKemk3Fu1UMD5cU5UYd",
                   "https://open.spotify.com/intl-pt/track/7KPhwNko8V9vYBIN653hSO",
                   "https://open.spotify.com/intl-pt/track/1m5nbZiPpCIi9J2irLNoxh",
                   "https://open.spotify.com/intl-pt/track/7BwjZ1jy4B0ZyXTY4YQM9A",
                   "https://open.spotify.com/intl-pt/track/1a1CZOOOgsm1bGf0G92Zrn",
                   "https://open.spotify.com/intl-pt/track/27x579ayIvantoVe6PP97U",
                   "https://open.spotify.com/intl-pt/track/1TL33F4bcT9fZPSqvUbFV5",
                   "https://open.spotify.com/intl-pt/track/0EuRZKWzNptC1ZuIMFKLxz",
                   "https://open.spotify.com/intl-pt/track/6b7bKdjQVs3Dzeqoz2s7uN",
                   "https://open.spotify.com/intl-pt/track/4phWuswkCNopB7piK6E8Mb",
                   "https://open.spotify.com/intl-pt/track/2HNTWEJx0FtU6UQfT01VR1",
                   "https://open.spotify.com/intl-pt/track/7M7oYTGSDkD1jfv33yWtR0",
                   "https://open.spotify.com/intl-pt/track/04yRKQeVouZn2gHCr1G6wU",
                   "https://open.spotify.com/intl-pt/track/5K1n3LwCVZg2TE9SLgIwem",
                   "https://open.spotify.com/intl-pt/track/6Y62EUa0zeCpH0NE9l643Z",
                   "https://open.spotify.com/intl-pt/track/5XhG8HGyxLrkJAASxLA463",
                   "https://open.spotify.com/intl-pt/track/6WgbUmH1yKA2YJ5NY2upOA",
                   "https://open.spotify.com/intl-pt/track/1jeg6gX21ljllOryvi9SJh",
                   "https://open.spotify.com/intl-pt/track/4JsUjwvt5GKqqM3skZDUzE",
                   "https://open.spotify.com/intl-pt/track/4fmcMtoFinvk20rhiyWL91",
                   "https://open.spotify.com/intl-pt/track/5rryOlcxbh700EuOa59waG",
                   "https://open.spotify.com/intl-pt/track/6xs35sD9WnoShqmJXfOj27",
                   "https://open.spotify.com/intl-pt/track/6gAD9BkdcEXM9X3ObuuWjC",
                   "https://open.spotify.com/intl-pt/track/7xPuG4zgAHk0f0Dqkp2Yig",
                   "https://open.spotify.com/intl-pt/track/0CeaAvEotqd1vxT25x2oQ2",
                   "https://open.spotify.com/intl-pt/track/7LNOsASVhU3pO6WlmNjt26",
                   "https://open.spotify.com/intl-pt/track/2goeywqmRTcpC9Lnx7GdIN",
                   "https://open.spotify.com/intl-pt/track/16LiytjyS2luV5pD6qJxiU",
                   "https://open.spotify.com/intl-pt/track/6hSs4NAiWub47nULLBtUj1",
                   "https://open.spotify.com/intl-pt/track/2Ptw1JNaLncVc6A9SnamMb",
                   "https://open.spotify.com/intl-pt/track/4PVDAebj5ADsLOBw1D9KbP",
                   "https://open.spotify.com/intl-pt/track/2UK3EhCjisvoPu0mAoGLP8",
                   "https://open.spotify.com/intl-pt/track/2peC0lAzDeR90bgmgdhqWd",
                   "https://open.spotify.com/intl-pt/track/3J4FUI8Oz0K1NTwdsXjeOl",
                   "https://open.spotify.com/intl-pt/track/7n2jDh2CY0QKs70hw6Dvyu",
                   "https://open.spotify.com/intl-pt/track/4NhVMeAFuBLKzEXQYp5yXx",
                   "https://open.spotify.com/intl-pt/track/69Flz1PeHxdGW0trMUNjll",
                   "https://open.spotify.com/intl-pt/track/0y7tbpW4aLlwV5PFvNbkL3",
                   "https://open.spotify.com/intl-pt/track/1R9QwNmWhWs9HLURsJvMuU",
                   "https://open.spotify.com/intl-pt/track/2qqm0N3gKH4h7ETlmvyOHo",
                   "https://open.spotify.com/intl-pt/track/457V49BhoC82JATzMaX7HJ",
                   "https://open.spotify.com/intl-pt/track/7j9VXymOY1GLQmXPcuaZmu",
                   "https://open.spotify.com/intl-pt/track/0LPviEkBJPMLwK6FHuFiKj",
                   "https://open.spotify.com/intl-pt/track/7qeJNEyuXaWmYsHyPmzbFv",
                   "https://open.spotify.com/intl-pt/track/2D3FXW4GvYbiZnhAdHPtLB",
                   "https://open.spotify.com/intl-pt/track/5oKcpuszlyGFFIfvMiyHwL",
                   "https://open.spotify.com/intl-pt/track/0IugBW2da8cfIZIVjlZ31C",
                   "https://open.spotify.com/intl-pt/track/07MA122PzVpwOLuVsyHBfR",
                   "https://open.spotify.com/intl-pt/track/6WiSS1WzxZNKHYpGy0isYI",
                   "https://open.spotify.com/intl-pt/track/1JHWUKjEkO4gMSsdpgAqOy",
                   "https://open.spotify.com/intl-pt/track/4hifNfdA1anCseJafm1F8a",
                   "https://open.spotify.com/intl-pt/track/5qrljVpWUHX3fAhJZqAIUa",
                   "https://open.spotify.com/intl-pt/track/12A2LExOGBY6aM9euKv2cJ",
                   "https://open.spotify.com/intl-pt/track/19rYsBUNClYidByVMkY3H1",
                   "https://open.spotify.com/intl-pt/track/0MIwsK3JVBwujwBuPmJKfh",
                   "https://open.spotify.com/intl-pt/track/1zY61KGbc7aeOdzlQpftSZ",
                   "https://open.spotify.com/intl-pt/track/2ye9BKhLI6xv7mOgXcq1PS",
                   "https://open.spotify.com/intl-pt/track/3hNm8sXtMbSehcrI4zdecG",
                   "https://open.spotify.com/intl-pt/track/1kxrDZEDihuelR3QlKJH7g",
                   "https://open.spotify.com/intl-pt/track/74uMkyhm8QY9XDjOou0t9i",
                   "https://open.spotify.com/intl-pt/track/1ndLx2LGQwdrpjqWrAutaJ",
                   "https://open.spotify.com/intl-pt/track/2S3ExR7GFtBJE5NvgqkM8J",
                   "https://open.spotify.com/intl-pt/track/7xIPKUknmpPaeQOarWbOBM",
                   "https://open.spotify.com/intl-pt/track/7iT4AuOMGUzqT0wnewEWjn",
                   "https://open.spotify.com/intl-pt/track/5g5CcCHsWnPfSALXDfew64",
                   "https://open.spotify.com/intl-pt/track/1vI2ZggrRcApRBfDq5WzDC",
                   "https://open.spotify.com/intl-pt/track/6sqibU9Tq9ZXYxY2DthWsT",
                   "https://open.spotify.com/intl-pt/track/5geU4byUA1hnQofQPOsPDS",
                   "https://open.spotify.com/intl-pt/track/1WD3DB710SmoFjhASWo10D",
                   "https://open.spotify.com/intl-pt/track/5R1h9ssiMJIDFAeEzGj9G0",
                   "https://open.spotify.com/intl-pt/track/54GJcQTcNBy09IvCUcXPtI",
                   "https://open.spotify.com/intl-pt/track/6oVNrpMWlzS6UkQuuM8zHU",
                   "https://open.spotify.com/intl-pt/track/54FV2rMVwLusAVnzROB0c1",
                   "https://open.spotify.com/intl-pt/track/4W7Y0EsaVPh87WKC1etOHA",
                   "https://open.spotify.com/intl-pt/track/38r9CzTvjFuEC4PrzRI78K",
                   "https://open.spotify.com/intl-pt/track/0GRsw57baGM62NQD3kpdEp",
                   "https://open.spotify.com/intl-pt/track/205be0Y9FaGNVz5HB8CTY8",
                   "https://open.spotify.com/intl-pt/track/1vI2ZggrRcApRBfDq5WzDC",
                   "https://open.spotify.com/intl-pt/track/4JsUjwvt5GKqqM3skZDUzE",
                   "https://open.spotify.com/intl-pt/track/16LiytjyS2luV5pD6qJxiU",
                   "https://open.spotify.com/intl-pt/track/6oVNrpMWlzS6UkQuuM8zHU",
                   "https://open.spotify.com/intl-pt/track/1jeg6gX21ljllOryvi9SJh",
                   "https://open.spotify.com/intl-pt/track/4NhVMeAFuBLKzEXQYp5yXx"],
}

# Initialize a dictionary to hold the duplicate URLs
duplicate_urls = {}

# Iterate through each artist in the dictionary
for artist, urls in artist_tracks.items():
    # Use a set to track seen URLs
    seen_urls = set()
    # Iterate through the URLs for the current artist
    for url in urls:
        # If the URL has been seen before, add it to the duplicate URLs dictionary
        if url in seen_urls:
            if artist not in duplicate_urls:
                duplicate_urls[artist] = []
            duplicate_urls[artist].append(url)
        else:
            # Add the URL to the set of seen URLs
            seen_urls.add(url)

# Print the duplicate URLs
for artist, urls in duplicate_urls.items():
    print(f"Duplicate URLs for artist {artist}:")
    for url in urls:
        print(url)
