from googleapiclient.discovery import build
from time import sleep
import csv

API_KEY = 'AIzaSyD74qS0b9EHk5P-wWMOXXqWk4HTe7Fas04'

BATCH_SIZE = 50

REQUEST_DELAY = 1


class YoutubeFeatFetcher:
    def __init__(self, api_key):
        self.youtube = build('youtube', 'v3', developerKey=api_key)

    def get_video_views(self, video_ids):
        video_info = {}
        batch_count = len(video_ids) // BATCH_SIZE + 1

        for i in range(batch_count):
            batch_ids = video_ids[i * BATCH_SIZE: (i + 1) * BATCH_SIZE]
            request = self.youtube.videos().list(
                part='snippet,statistics',
                id=','.join(batch_ids)
            )
            response = request.execute()

            for item in response.get('items', []):
                video_id = item['id']
                title = item['snippet']['title']
                view_count = int(item['statistics']['viewCount'])
                video_info[video_id] = {'title': title, 'views': view_count}

                print(f"Fetched views for video '{title}': {view_count}")

            sleep(REQUEST_DELAY)

        return video_info


def initialize_artist_videosytfeat():
    return {
        "Mainstreet": ["", ""],

        "Orochi": ["jK2k1P56Cno",
                   "oYQwySDMl9w",
                   "n43oZSY7df0",
                   "3aKrgl3-Unc",
                   "paYdjXDYX4U",
                   "KAhADAUje9g",
                   "zjOARjnWdhA",
                   "I6-MS7YqDso",
                   "oYQwySDMl9w",
                   "l3glrN_Ppn4",
                   "UJ835PU_DNs",
                   "rx1u5_SnzlAd",
                   "KrLnAuQXDSA",
                   "Y69kiJ3fRr8",
                   "pJKTTca3_B8",
                   "CC08dwBPT6o",
                   "BzcIno-D0Es",
                   "OcXQbudiOhg",
                   "oqEZzLb4oqM",
                   "mJ2eHyAej9E",
                   "RSTA5ZmJwVE",
                   "ieLxPJnumbQ",
                   "pwTkvWMe-mM",
                   "ZByR-GeWtrE",
                   "0zcGA9XtpbQ",
                   "_mVRfzZxhD8",
                   "SZ1H5lIOIuU",
                   "aZLIddtdTqI",
                   "Hw8RPU08JHY",
                   "mB8CrTw6Ns4",
                   "ionXEeQwHwc",
                   "kEzi0RmMi7Y",
                   "6OfetYxWNTg",
                   "YkBiDJS19ggd",
                   "vT1opSL_7hY",
                   "TbTTr4vdxl0",
                   "v9dMpHngeho",
                   "5KR9i_lbP_I",
                   "QPHwnonmegA",
                   "uQ9qosnDVIM",
                   "RNFOzKepUIQ",
                   "02YrqzFsydw",
                   "wyYnNPV4328",
                   "rwcoCoxvxiY",
                   "Z1wXASHFvdA",
                   "JStt5nyiIvU",
                   "kTjV6wet8oc",
                   "npdQ24oIDAk",
                   "Ms-H7JxHIaY",
                   "vJ7sEgEWHsA",
                   "zDNXdVHgrAc",
                   "MPNrT2csQBE",
                   "-5gT-c9IEDM",
                   "M_rb_yE1kMo",
                   "RypZnwPtfd0",
                   "7IlBLB9XkGQ",
                   "QD8EWFCQ4VY",
                   "DNd07SBmqEQ",
                   "GB3aoOOhoOk",
                   "2HFexfq4Caw"
                   ],

        "Mc Poze do Rodo": ["1NY-2dZphF0",
                            "2PRAiVs3MVc",
                            "N6Rao_x2cJc",
                            "FMWiJwLG0j4",
                            "yisekBimeBI",
                            "hyDElqwFnYI",
                            "3aKrgl3-Unc",
                            "XNROQyD5EH8",
                            "SslgMAOJZwI",
                            "WO52f2MsYzk",
                            "KrLnAuQXDSA",
                            "76_J1jZLp5s",
                            "MNrIQxcNuTQ",
                            "A_EWrzI2CUg",
                            "ofRCBvm3Muc",
                            "3855RydvJVA",
                            "CC08dwBPT6o",
                            "ajBNJ7P4T7I",
                            "ALGMBN8GL_I",
                            "7ZUe-cHbVU8",
                            "dCVcOB8dfr0",
                            "KWLCz-sd7J0",
                            "_7V-gFxYD-Q",
                            "kaqF91IFegg",
                            "4IKM9Cy9maA",
                            "NVrQ-wjws7c",
                            "LPoiJec6Vqk"],

        "BIN": ["6BgxLcofzoo",
                "l3glrN_Ppn4",
                "VANSAIGXsDw",
                "Tx6K_tSgep8",
                "NkbOmC6kK-c",
                "Y69kiJ3fRr8",
                "syRNIi9zLy8",
                "7L4cWt1G3j4",
                "bhXUrS--eFs",
                "1HO15l5EGvE",
                "sOd5-2RskiU",
                "D9MtpH2ZE2U",
                "lIFAB34-xkM",
                "v-dLApGFbHE",
                "iDY-SN-DHwI",
                "Gd6fjog75wE",
                "XbEwIUUfrXk",
                "IjvvyKkw1jE",
                "c4XECQVA9qc",
                "eR3InvME-rg",
                "gp7QAVTTx3Q",
                "zmlNLw6iVdY",
                "9u3rrHW6mXY",
                "lBZxEYFq8eI",
                "WH0kEMbf1qg",
                "H7Vp0XVH09Y",
                "jJGX6IGcPlE",
                "aCjf_i5Lfj8",
                "E6FvqDOg4tQ",
                "e8nzuaNBww4",
                "-tuwzPvyKzA",
                "LV7mtzQXHdE",
                "FrnKOZzHXu4",
                "LxW6iWz6JFY",
                "JWSY5MBqbsU",
                "ginJvcY5i7w",
                "5NzWV-YylEs",
                "d-CgSQ17pdA"],

        "Borges": ["ODBw-Ch6V9E",
                   "OpU9Q8xMYSs",
                   "l3glrN_Ppn4",
                   "VANSAIGXsDw",
                   "UJ835PU_DNs",
                   "cyy4HCL8bmg",
                   "d-sTHIecSBw",
                   "KrLnAuQXDSA",
                   "RiYQ90oyYBw",
                   "nd_m17VsRh0",
                   "UZxnSc6VKog",
                   "S9ZK79QhwgY",
                   "6iAb5K0bDTw",
                   "KQQPCBmqOh0",
                   "I7AKk5eCgVM",
                   "XehBL50Q2m4",
                   "RtRGjVtVVrQ",
                   "0hO9pFXkESs",
                   "hndoi6pVzLI",
                   "sOd5-2RskiU",
                   "D9MtpH2ZE2U",
                   "qxB3anjq4Pc",
                   "8JFcR_PQMpo",
                   "15bgB21zInE",
                   "nfGYAmj0b6k",
                   "SHJd2yZNtb0",
                   "cfzKdBY9Kaw",
                   "dCVcOB8dfr0",
                   "4iknmmyXuR0",
                   "iu2quj6lNKA",
                   "XfhmsPMjlhQ",
                   "m1vtV87t9fE",
                   "36E8GiTmp7I",
                   "yB9pwxOx14E",
                   "vSPtpYHfs1E",
                   "vxfRqcUdFcY",
                   "kxQZAYGSngw",
                   "pBWbvMtgrZU",
                   "1Ss4F0IUcv4",
                   "MnhQ98BBLeI",
                   "I-9lBqezYVM",
                   "0Ta2EdomFPU",
                   "3_UFPYTNgjg",
                   "Y8FPy5OVKsk",
                   "iWfZQPYTQ38",
                   "vE3qv7MsBUE",
                   "1_UKb-CvWnk"],

        "Chefin": ["YPlY9bCyDaA",
                   "OTrXfWSl7bw",
                   "T2BQG_8CFHI",
                   "s8EnhrR9Hxs",
                   "69-jnA4QLSM",
                   "t43c5QW4GXA",
                   "79KWwlhbOD8",
                   "Ww056PGMT8Y",
                   "n43oZSY7df0",
                   "QrKmPd-Ai_U",
                   "0yPQnBG0hzQ",
                   "N9liPvylviE",
                   "91Fw8XnqHy4",
                   "rQ6jjQ9jE0E",
                   "tsY_cCkGgM8",
                   "6jIdiTzBSkw",
                   "yXbeZ8qXDQA",
                   "iTZjA_BIPaU",
                   "t8OuCgrIXNg",
                   "KrLnAuQXDSA",
                   "kC8X06J4Q8Q",
                   "ec7quUelat8",
                   "kAgw1Gkw10U",
                   "6iAb5K0bDTw",
                   "WVndi9ppDyo",
                   "mJ2eHyAej9E",
                   "RSTA5ZmJwVE",
                   "1G3F42KeBiQ",
                   "3PVkxOaTIU0",
                   "sisGy19Vt78",
                   "-gysEtnzYEw",
                   "AWUMbVKr8r8",
                   "7Zd09_o608w",
                   "AERWeIkBrl0",
                   "0eieSZEFewI",
                   "cY7NVK5LqOg",
                   "-D_HejAuy4A",
                   "1eDxIr03R-E",
                   "UR-ROJP92pc",
                   "9Ve1ZolHwVM",
                   "gp7QAVTTx3Q",
                   "pVdCQqUzGdg",
                   "f0WcGsJwgxo"],

        "Oruam": ["cOwseUbtW8A",
                  "1NY-2dZphF0",
                  "90NdQknZkfM",
                  "9aWC3Z3hjII",
                  "qUAfc4XuWGw",
                  "s8EnhrR9Hxs",
                  "hr_83ZXhmOI",
                  "24lfgigKHqQ",
                  "69-jnA4QLSM",
                  "N6Rao_x2cJc",
                  "ysn8Ifdfry4",
                  "kWvFoR-Wf-I",
                  "OS23TZIPCLA",
                  "79KWwlhbOD8",
                  "5hj2kiGGbGs",
                  "n43oZSY7df0",
                  "n2vr0aGhvTc",
                  "dUC7TBmzrL4",
                  "WO52f2MsYzk",
                  "KrLnAuQXDSA",
                  "oFl6nZwxgxI",
                  "6iAb5K0bDTw",
                  "CD_tFnM6Yd0",
                  "kqPSfz_bCX8",
                  "d3S5PZIjA_0",
                  "lIFAB34-xkM",
                  "c3lpz4JKTUo",
                  "aKTjSCn9x-8",
                  "N6Rao_x2cJc",
                  "-Suh_YfIRAk",
                  ""],

        "Bielzin": ["2PRAiVs3MVc",
                    "N6Rao_x2cJc",
                    "hyDElqwFnYI",
                    "3aKrgl3-Unc",
                    "6nT50nEGINk",
                    "oq5dmtQhoHU",
                    "7L4cWt1G3j4",
                    "rnhrtIfi-HU",
                    "15bgB21zInE",
                    "hQBeY2pqZ6c",
                    "kOAz5r4hegs",
                    "z-LxlqAXh24",
                    "MHWAbze14Ak",
                    "Wu7-MxFRwU0",
                    "kMXEtoSQX-E",
                    "kaqF91IFegg",
                    "r_yGe0bFr7s",
                    "eCpU8IsCUPE",
                    "_Mfq9xUim1w",
                    "ieNva_S8MXQ",
                    "VhyvsSn-6yA",
                    "Nce_wQqORS8",
                    "xxsGLy_5Wbo",
                    "tWmTHns2vKQ",
                    "7SvCM5XqPAc",
                    "nUtqsM4fpyM",
                    "JUPnbsvWSsc",
                    "bMVLhP1810I",
                    "0tKNWp9GVCU",
                    "upH8KxM3iSg",
                    "Q8DRkx5GHno",
                    "LGYNIoywU0c",
                    "5aFApwiiap4",
                    "LtYvTIADaKs"],

        "Dfideliz": ["fPwdWahrjgg",
                     "SnZBwzj8Zyw",
                     "aBPU4f6rH-w",
                     "DqQFwivXqxI",
                     "5NP-V589lJc",
                     "1HO15l5EGvE",
                     "P7D4eOpondM",
                     "Ekfl_FfNqCg",
                     "jfdJ1KTA7oA",
                     "0qK7rgf_zIM",
                     "rEaheZiIRVU",
                     "VZJEHxAU_l4",
                     "qs7h_2rign8",
                     "ozSWc_j07FM",
                     "Jie46YL1ARI",
                     "9STYlSYuGnU",
                     "UlgrkPuhAIk",
                     "pTlcl7aTG_o",
                     "If_SyoKzjA0",
                     "rSa9jBvZ2FE",
                     "HOwLf15CXDY",
                     "paQseIx5XCY",
                     "rmgECCU6NVo",
                     "ImpXab4WsNM",
                     "6uF4PeDMS64",
                     "OBVrA4NaZoo",
                     "k6RdHVBIGgw",
                     "PKru7Km50sE",
                     "6Io86u2S1xE",
                     "_Oj2EkZSvZY",
                     "p-6IxmbKx18",
                     "wsumfCM5I1U",
                     "NMMYFjkOqVg",
                     "3WNJApOwcvI",
                     "R6ravsRdXLo",
                     "5fvf57Xs_5w",
                     "gZD-MPSggCI",
                     "45C6HqqqPVc",
                     "StpsccPzH2w",
                     "TtPNIRnIX-w",
                     "Ydk0I8F2Nkg",
                     "xs3dV27tC7Q",
                     "VAkxUzJNZdQ",
                     "CkJiZu175xo",
                     "NY09D_-Ull4",
                     "DqQFwivXqxI",
                     "Jie46YL1ARI",
                     "zfYyRpgtoWQ",
                     "jCKfXa95VSA",
                     "EZBWYMOwg_I",
                     "k3un2ZQOUXA",
                     "3PrrIxOpprE",
                     "rxhJeFhEKMI",
                     "R7FHpW9liKY",
                     "ZnQWQ2QxCZo",
                     "oockZLkqbyw",
                     "O7CnH3UEbJI"],

        "PL Quest": ["2PRAiVs3MVc",
                     "6BgxLcofzoo",
                     "l3glrN_Ppn4",
                     "VANSAIGXsDw",
                     "qxB3anjq4Pc",
                     "0qK7rgf_zIM",
                     "ieLxPJnumbQ",
                     "q26rES2f74s",
                     "pPN2IQbF4xQ",
                     "aPEKDyVubQg",
                     "nbbC6RJ1V0s",
                     "osHwSqcIo-M",
                     "JAq2ol2MJRA",
                     "-LM5LEEP-j4",
                     "ospxD6iryWg",
                     "7SvCM5XqPAc",
                     "AgS9AWmOY_I",
                     "wRG9QBrFz3s",
                     "Kk8kcOP3DC4",
                     ""],

        "Raffé": ["79KWwlhbOD8",
                  "BJa8zgf0cdQ",
                  "WO52f2MsYzk",
                  "Z9laTuc3bcs",
                  "7L4cWt1G3j4",
                  "BzcIno-D0Es",
                  "VW5ujnrRDTg",
                  "HBt0YK0X5RY",
                  "P_Ba0Zr6neM",
                  "oyPidHxm984",
                  "CeDljHB-EEM",
                  "gE8C8kim81E",
                  "QFxvp06W694",
                  "XuuoTqu2yQk",
                  "kHuvJZ5kkKY",
                  "-W7TuhCDi-M",
                  "oxoLOPHoTlY",
                  "lksyHqm7M6Q",
                  "BK8Om7KObO8",
                  "7d0sdZr6Gng",
                  "KnIwJyThrlE",
                  "odaOK-M2jxc",
                  "B_mwFMXcgI8",
                  "4ZOq8-8FsCU",
                  "zN79Os7DmHY",
                  "xP3orzQz6sM",
                  "vopfn1FNDgo",
                  "ugUmaOrYx6Q",
                  "nX33TGuJ15E",
                  "zcPITugjdc0",
                  "f0WcGsJwgxo",
                  "JxaMoRbS7kI",
                  "OTAM6JX1M48",
                  "0dcWHc2Tsdk",
                  "QPYUMO0leyw",
                  "Jvhb3ET38YI",
                  "0XzZPyM3BB0",
                  "3NhB2Q6iZHA",
                  "34HyXxCnj2k",
                  "rxocGB-xxy8",
                  "Z4Fu8bMzsOw",
                  "nlWKdSY_2ig",
                  "kt_kIwzs60I",
                  "-7miA2e3NLs",
                  "SLiz8tej4AY",
                  "pYueRjEoZDw",
                  "vFxRWy1tfaE",
                  "MwqHJl0L2dA",
                  "eyOjbElwf6w",
                  "7d0sdZr6Gng",
                  "_OVVjAISnwQ",
                  "iv2y76HT24I",
                  "hjBdJVkkVK8",
                  "A1IJNW7q6Ok",
                  ""],

        "Azevedo": ["l3glrN_Ppn4",
                    "VANSAIGXsDw",
                    "ofRCBvm3Muc",
                    "0qK7rgf_zIM",
                    "ieLxPJnumbQ",
                    "0zcGA9XtpbQ",
                    "jRZ73fzM2ck",
                    "cM6apns26UM",
                    "TWZPignwC5M",
                    "5KR9i_lbP_I",
                    "igYePv-u1JU",
                    "v9dMpHngeho",
                    "zmlNLw6iVdY",
                    "q2p5lSK2mXU",
                    "7ZOZYeJxczw",
                    "Oia1yrePjC8",
                    "Iz44nZh9vng",
                    "-tuwzPvyKzA",
                    "kIQVrRkl1PQ",
                    ""],

        "Leviano": ["WVndi9ppDyo",
                    "co3i5BD5REQ",
                    "xMfvCBjXDuo",
                    "8q1dfQh6Xvw",
                    "FGdvPxT7jUA",
                    "gEN8OvlTIbk",
                    "YMppcV9Oxlk",
                    "olCSt4ECMb4",
                    "ay9QbRAuEgc",
                    "gGbBwMVgbMw",
                    "l5rHj33P2Pg",
                    "vxDkpcUeal8",
                    "ItWZP06sdOg",
                    "W5cW8se4IgQ",
                    "bJVWVrkHiZg",
                    "2Z275rX2kqs",
                    "MmstcqsI0IA",
                    "cMz4ahS64PI",
                    "mOjzW3qLU-8",
                    "AnPh7qsjMNc",
                    "xpv54igecQM",
                    "mCF3TmT3yeg"],

        "Ajaxx": ["ajBNJ7P4T7I",
                  "7Zd09_o608w",
                  "MZ6kM3eVQB0",
                  "siqSKgaPD-c",
                  "Wu7-MxFRwU0",
                  "mvgkbVkSxq8",
                  "fHKe0fQfY-8",
                  "2sBdz4GSCi8",
                  "zvyN63eV7II",
                  "PwtUW0cgEgs",
                  "CTHm-MRxl58",
                  "HhR1wqiApJc",
                  "IjvvyKkw1jE",
                  "-D_HejAuy4A",
                  "nOF-ddKIkzA",
                  "pBWbvMtgrZU",
                  "ucOYbNa4c2c",
                  "yp1GYpC3h_o",
                  "US53RDdsMRw",
                  "wyYnNPV4328",
                  "MU23J0oMTu8",
                  "ugUmaOrYx6Q",
                  "nX33TGuJ15E",
                  "NWDcy9uCBGU",
                  "9VVYe6uirQM",
                  "XJOpG60Jjug",
                  "277xNtPMiLM",
                  "QPYUMO0leyw",
                  "7zaS4MnPtRw",
                  "VW5ujnrRDTg",
                  "v9W9RCHJnFw",
                  "_DiJuGAtVWs",
                  "m4ltJtZsz0Q",
                  "Uw7z7WsjtRc",
                  "EcJgPAm9E1o",
                  "7XF9lqwQCug",
                  "cIz_P0vRU30",
                  "rY5-1MR0qss",
                  "sYSLUfDyDGw",
                  "bMVLhP1810I",
                  "L_gRVzw8yY4",
                  "qjKATCsYGEk",
                  "I-hRI9FLjM8",
                  ""],

        "Kizzy": ["ba969xr3krs",
                  "24lfgigKHqQ",
                  "VANSAIGXsDw",
                  "l3glrN_Ppn4",
                  "arapddN0bfc",
                  "qr8ET9SbOgw",
                  "nRWP65v1a1o",
                  "iY9s37ExYQk",
                  "u6ybSSTe-9E",
                  "GVIz0O605cE",
                  "6VmZoGLJNY0",
                  "U-n1RlLBwYk",
                  "UcBuFEDjDdY",
                  "wr2q5k0FX_Q",
                  "bQnOR-h3-TA",
                  "TonvLOhEv_U",
                  "fAzb_qu4LBw",
                  "q2p5lSK2mXU",
                  "f_ZuSn1sMx8",
                  "ffWGhCgeJ7o",
                  "6BgxLcofzoo",
                  "tHxOgMIUxvY",
                  "mn937Jdqlmo"],

        "jess beats": ["Ql3cVo2f9Sg",
                       "e8j6mmp3W0E",
                       "qr8ET9SbOgw",
                       "ofRCBvm3Muc",
                       "FR3NDWKNA44",
                       "QV8BimeAvbc",
                       "QzeAJrXOdJk",
                       "TqrJszrcKpM",
                       "RFqN8xx-h30",
                       "8q1dfQh6Xvw",
                       "hQBeY2pqZ6c",
                       "f6kNhWc__FM",
                       "Tdxzntll32U",
                       "8ku4EouyRL8",
                       "-L1_1-iErw0",
                       "tPcwYGqkFEA",
                       "4GukYsC1DXY",
                       "3lH5mVl8HWc",
                       "HBzH7GhOU48",
                       "ffVywcCk8tw",
                       "2BBJg_AxzQg",
                       "oqjp9DU5BLE",
                       "YosJYGKHTPk",
                       "j-ttUGgDk6U",
                       "R_BSdnySVLg",
                       "Kldmvn9Iq3E",
                       "5NFIpIrS8BQ",
                       "kR-yJo_4dBw",
                       "nLHrIZ_KL-8",
                       "Nj9Y0galntM",
                       "nB0me_mG3Is",
                       "YxnFIkwERE0",
                       "HD-8KjVBp8E",
                       "tDqX066X3eo",
                       "Xddfo0V5-MY",
                       "qRZSblGLzFM",
                       "k5CYwCAKmxM",
                       "LCbITtKSHaM",
                       "sSZwX22oY0E",
                       "CsmO8KyQ-6k",
                       "CNtohjWq_h0",
                       "PYUhoVTDKOw",
                       "XLA_sMP73q0",
                       "b59uYHLp9xg",
                       "rr2l6jK0ews",
                       "JJI8rAEn7_M",
                       "Pzf8PP0YR98",
                       "BoeW7QOJlHY"],

        "RUXN": ["ba969xr3krs",
                 "3WGlmbKjmPY",
                 "l3glrN_Ppn4",
                 "VANSAIGXsDw",
                 "pbYwQDjz_4E",
                 "jEfzdMymlgs",
                 "u6ybSSTe-9E",
                 "GVIz0O605cE",
                 "0qK7rgf_zIM",
                 "q26rES2f74s",
                 "BY8e6rzDiMM",
                 "cuu4KdTwfoU",
                 "o1r4YtfWlec",
                 "ionXEeQwHwc",
                 "kEzi0RmMi7Y",
                 "gX57i6w3mN4",
                 "q4Upt1JeRAo",
                 "5gHdJ2B8_kg",
                 "ubtEoq5gW7U",
                 "vuq_-8eZn0I",
                 "ot-1uHlTQGI",
                 "bQnOR-h3-TA",
                 "o1r4YtfWlec",
                 "fK8oxXwSeMY",
                 "uHaDRs_9jT8",
                 "8KNnRc_XNwI",
                 "EoMoMBF52w0",
                 "_Khl1cOnqT0",
                 "4CFaWELaFRE",
                 "En_JnmuylDs",
                 "rN9dqa3LKfw",
                 "f1a1aqT2a9E",
                 "8qSKRMu0AE0",
                 "VD5JNeP5Jp8",
                 "jMiTSHeMf50",
                 "N2riiPPVbo0"],

        "MC Cabelinho": ["ba969xr3krs",
                         "QQw_eox2sDE",
                         "jK2k1P56Cno",
                         "2PRAiVs3MVc",
                         "69-jnA4QLSM",
                         "N6Rao_x2cJc",
                         "4cr9HDJsls4",
                         "ENHwrVK0wn8",
                         "m3TuA6_cVZI",
                         "iDCj3zwQXKs",
                         "JavGACaJx0Y",
                         "3WGlmbKjmPY",
                         "2HFexfq4Caw",
                         "q35csn_vnSs",
                         "KAhADAUje9g",
                         "EcaOO99_fLI",
                         "Laz0wVM7byI",
                         "Xhv4bEawTuM",
                         "I6-MS7YqDso",
                         "q9U-k9rd0EY",
                         "stjSIweo0UY",
                         "vhTrtN7e2bs",
                         "3FqvSErFDcs",
                         "gLcFWEkebZ4",
                         "q-uWWNcu724",
                         "FjL96lJGa8Q",
                         "B7ALF7UpmvQ",
                         "37U5GWqKYMs",
                         "k783VpYRBl4",
                         "rnhrtIfi-HU",
                         "WaevbxLlDPA",
                         "7KWllvhaOyc",
                         "SZ1H5lIOIuU",
                         "jh2N79XOSTY",
                         "P69_28Sw82Q",
                         "C6x0yRQjyrw",
                         "Q-5fE8ahl5I",
                         "9Ve1ZolHwVM",
                         "Q2O2cVIEozs",
                         "b40e90xdxbg",
                         "NDaqfhvGfec",
                         "OXtoJAAe_is",
                         "TP3U89YFsXA",
                         "kNzf8nCAeyM",
                         "dIKjQqXfqfw",
                         "L29Rw6onvF8",
                         "PzN5cKd0tSU",
                         "f-cZ_6HTNm8",
                         "UUaIiMxvRGs",
                         "nSlpBqajC9A",
                         "0J_pZRRTXTQ",
                         "4cr9HDJsls4",
                         "SI_HIvpuPNQ"],

        "Brutos": ["5t0J5Yt4eI0",
                   "BeiNi92zokg", ],

        "A.R": ["BeiNi92zokg",
                "5t0J5Yt4eI0"],

        "Vinicin": ["5t0J5Yt4eI0",
                    "r_yGe0bFr7s",
                    "0CG4C0yWQKw",
                    ],

        "MANO R7": ["PmgZI1I02Ls",
                    ],

        "Amorim": ["BeiNi92zokg",
                   "5t0J5Yt4eI0"],

        "Buddy": ["qxB3anjq4Pc",
                  "UMqrjIKOClI",
                  "hzvndtoZCPo",
                  "CNtohjWq_h0"],

        "Mvk": ["LPoFbsAT1sE",
                "NA1UqUuqnQ4",
                "UR-ROJP92pc",
                "NA1UqUuqnQ4",
                "HkeYAKOgm3I",
                "UacEnZDwmaM",
                "uwkBATNtEb4",
                "JGNPfkzIN_c",
                "ZlagbA9GJwM"],

        "Pedrin": ["QzeAJrXOdJk",
                   "TqrJszrcKpM",
                   "eBJCpHhSYnM",
                   "xBvMz2i0oEM",
                   "gIlrTv7JMRk"],

        "Mc Filhão": ["bnjpTybzCBQ",
                      "f98313sqECM",
                      "YyG9VrNVrC8",
                      "2DgiiDWpHpk",
                      "DGQgQ4FKgyU",
                      "14R6dIe5LQg",
                      "SrzEZ89zwHY",
                      "qpeeQhQYjzg",
                      "ZlagbA9GJwM",
                      "HvrFySU0Bxs"],

        "Shenlong": ["FR3NDWKNA44",
                     "l3glrN_Ppn4",
                     "CC08dwBPT6o",
                     "0qK7rgf_zIM",
                     "ahrOERDQVpU",
                     "aZLIddtdTqI",
                     "QsgZ-rk39ao",
                     "jRZ73fzM2ck",
                     "cM6apns26UM",
                     "eR3InvME-rg",
                     "qpeeQhQYjzg",
                     "Oia1yrePjC8",
                     "PjEDQ-h8WGY",
                     "Lys1Az6LGSc"],

        "DEGE": ["ig3CcXrcQPU",
                 "-_KhPt9XB80", ],

        "Hashi": ["gIlrTv7JMRk",
                  "qpeeQhQYjzg",
                  "n6XKe5UtX3s",
                  "c_EYvWOYVcU",
                  "HvrFySU0Bxs",
                  "O9wmifOpDwA",
                  "ArZX6Wh1-68",
                  "ZlagbA9GJwM"],

        "Beny Free": ["-L1_1-iErw0",
                      "V7S5BYb93kE",
                      "ospxD6iryWg",
                      "7zaS4MnPtRw",
                      "xBvMz2i0oEM",
                      "7SvCM5XqPAc",
                      "cIz_P0vRU30",
                      ""],

        "Feek": ["f_ZuSn1sMx8",
                 "qpeeQhQYjzg",
                 "HpuvuIf7fBE",
                 "HvrFySU0Bxs",
                 "O9wmifOpDwA",
                 "-_KhPt9XB80",
                 "ArZX6Wh1-68",
                 "biGfq7cAIi4",
                 "y8-NV5uauH0",
                 "cIz_P0vRU30",
                 "LaWC67eAIcM",
                 "6oaZSmqr8_w",
                 "8ZZGrRMe490",
                 "TRlPrauDMVo"],

        "Oliveira": ["qpeeQhQYjzg",
                     "HvrFySU0Bxs",
                     "O9wmifOpDwA",
                     "0XzZPyM3BB0",
                     "Vg0AvYu0nPU",
                     "2F3dVf787Bs"],

        "Pior Versão de Mim": ["T1opSL_7hY",
                               "NyrNE4Bu1T4",
                               "84PnmwCwXMI",
                               "-_KhPt9XB80",
                               "nlWKdSY_2ig",
                               "aV2ptVp6lX0",
                               "8HuORPSgWOM",
                               "ArZX6Wh1-68",
                               "biGfq7cAIi4",
                               "ezdsaw3nbfs",
                               "9i8vcZV0LFk",
                               "ZRQCS51yefI",
                               "TyN-H7VMeY8",
                               "djoNPnq7zy0",
                               "q7F3_ISnke0",
                               "1kqxn_1JXew",
                               "eX66MaCC0fM"],

        "Oreozin": ["-_KhPt9XB80",
                    "ZlagbA9GJwM",
                    "TfJOPv2B2Bg",
                    "qpeeQhQYjzg",
                    "fF-bwGIt7Wc",
                    "HvrFySU0Bxs",
                    "-_KhPt9XB80",
                    "5g2fXVVjVcc",
                    ""],

        "Peziinho": ["gIlrTv7JMRk",
                     "UmpuRo7mAbg",
                     "s3uX4W6dpbE"],

        "Grone": ["-c-yp-EbQaQ",
                  "ArZX6Wh1-68",
                  "ghnaoSBYYbw",
                  "XhOSkk3ZXUc",
                  "icL7JzG6hTc",
                  "SPvobF6S3kc",
                  "vCv8CRzPzUI",
                  "SLHZMAEpKUk",
                  ""],

        "Vt no beat": ["oFl6nZwxgxI",
                       "5gHdJ2B8_kg",
                       "er4I--P27Fo",
                       "3zFxj3KXsOQ",
                       "pF1AZHA1ziI",
                       "ig3CcXrcQPU",
                       "YjmjT1hljMA",
                       "O9wmifOpDwA",
                       "-_KhPt9XB80",
                       "aV2ptVp6lX0",
                       "ArZX6Wh1-68",
                       "9i8vcZV0LFk",
                       "AJu6NwNvUOo",
                       "qbCksA6_5lM",
                       "4zhowmwBCuw",
                       "iExnrlDlK94",
                       "Xqlxd5_2SQs",
                       "1jj1Ehv4Pes",
                       "o33xwZbveTE",
                       "o33xwZbveTE",
                       "5LQThdos0aE",
                       "dn3u9w1qG8U"]

    }


def calculate_total_viewsytfeat(video_manager, artist_videos):
    total_views = {}

    for artist, video_ids in artist_videos.items():
        print(f"\nCalculating total views for {artist}:")
        video_views = video_manager.get_video_views(video_ids)
        total_views[artist] = sum(video_info['views'] for video_info in video_views.values())

    return total_views


def export_to_csvytfeat(total_views):
    with open('data/ytfeat_total_views.csv', 'w', newline='') as csvfile:
        fieldnames = ['Artist', 'Total Views']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for artist, views in total_views.items():
            writer.writerow({'Artist': artist, 'Total Views': views})


if __name__ == "__main__":
    artist_videos = initialize_artist_videosytfeat()

    video_manager = YoutubeFeatFetcher(API_KEY)
    total_views = calculate_total_viewsytfeat(video_manager, artist_videos)

    if total_views:
        print("\nTotal views for each artist:")
        for artist, views in total_views.items():
            print(f"{artist}: {views}")
        export_to_csvytfeat(total_views)
        print("Data exported to 'ytfeat_total_views.csv'")

    else:
        print("No videos found.")
